# This is a basic workflow to help you get started with Actions

name: create new PDF from Markdown on every tag

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    tags: 
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: mkrakowitzer/actions-makepdfs@v1.3
        with:
          # Location of markdown files in github repository
          markdown_dir: .
          # Location to output PDF files to
          output_dir: tmp
